addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.0.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.2.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"    % "1.4.2")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.4.2")