addSbtPlugin("com.geirsson"      % "sbt-scalafmt" % "1.6.0-RC3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"    % "1.3.15")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.3.4")